export enum PATHS {
  MAIN = "/",
  SIGNIN = "/signin",
  SIGNOUT = "/signout",
  EXPLORE = "/explore",
  SEARCH = "/search",
  DISCOVER = "/discover",
  ABOUT = "/about",
  CONTACT = "/contact",
  FAQ = "/faq",
  TERMS = "/terms",
  PRIVACY = "/privacy",
  COOKIES = "/cookies",
  MANAGERS_BASE = "/managers",
  TENANTS_BASE = "/tenants",
  MANAGERS_NEW_PROPERTY = "/managers/newProperty",
  MANAGERS_PROPERTIES = "/managers/properties",
  MANAGERS_SETTINGS = "/managers/settings",
  TENANTS_SETTINGS = "/tenants/settings",
  TENANTS_FAVORITES = "/tenants/favorites",
}
